language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.10.2
  - 2.10.3
  - 2.10.4        
  - 2.11.0
  - 2.11.1
jdk:
  - oraclejdk7
  - openjdk6
notifications:
  email:
    - gvojin@gmail.com
branches:
  only:
    - master
