language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.11.1
jdk:
  - oraclejdk7
notifications:
  email:
    - gvojin@gmail.com
branches:
  only:
    - master
