language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.10.4
  - 2.11.12
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
  - 2.12.4
  - 2.12.5
  - 2.12.6
  - 2.12.7
  - 2.12.8
  - 2.13.0-RC1
jdk:
  - oraclejdk8
notifications:
  email:
    - gvojin@gmail.com
branches:
  only:
    - master
    - record-operations
